migrate(
  (app) => {
    const minhaEmpresa = new Collection({
      name: 'minha_empresa',
      type: 'base',
      listRule: "@request.auth.id != '' && user = @request.auth.id",
      viewRule: "@request.auth.id != '' && user = @request.auth.id",
      createRule: "@request.auth.id != ''",
      updateRule: "@request.auth.id != '' && user = @request.auth.id",
      deleteRule: "@request.auth.id != '' && user = @request.auth.id",
      fields: [
        {
          name: 'user',
          type: 'relation',
          required: true,
          collectionId: '_pb_users_auth_',
          cascadeDelete: true,
          maxSelect: 1,
        },
        // Seção 1: Dados da Empresa
        { name: 'razao_social', type: 'text', required: true, min: 2 },
        { name: 'nome_fantasia', type: 'text', required: true, min: 2 },
        { name: 'cnpj', type: 'text', required: true, min: 14, max: 18 },
        { name: 'inscricao_estadual', type: 'text', required: false },
        { name: 'inscricao_municipal', type: 'text', required: false },
        {
          name: 'regime_tributario',
          type: 'select',
          required: false,
          values: ['Simples Nacional', 'Lucro Presumido', 'Lucro Real', 'MEI'],
          maxSelect: 1,
        },
        { name: 'data_abertura', type: 'date', required: false },
        {
          name: 'porte',
          type: 'select',
          required: false,
          values: [
            'MEI',
            'Micro Empresa',
            'Empresa de Pequeno Porte',
            'Média Empresa',
            'Grande Empresa',
          ],
          maxSelect: 1,
        },
        // Seção 2: Endereço
        { name: 'cep', type: 'text', required: false },
        { name: 'logradouro', type: 'text', required: false },
        { name: 'numero', type: 'text', required: false },
        { name: 'complemento', type: 'text', required: false },
        { name: 'bairro', type: 'text', required: false },
        { name: 'cidade', type: 'text', required: false },
        {
          name: 'estado',
          type: 'select',
          required: false,
          values: [
            'AC',
            'AL',
            'AP',
            'AM',
            'BA',
            'CE',
            'DF',
            'ES',
            'GO',
            'MA',
            'MT',
            'MS',
            'MG',
            'PA',
            'PB',
            'PR',
            'PE',
            'PI',
            'RJ',
            'RN',
            'RS',
            'RO',
            'RR',
            'SC',
            'SP',
            'SE',
            'TO',
          ],
          maxSelect: 1,
        },
        { name: 'pais', type: 'text', required: false },
        // Seção 3: Contato
        { name: 'telefone_comercial', type: 'text', required: false },
        { name: 'celular_whatsapp', type: 'text', required: false },
        { name: 'email_comercial', type: 'email', required: false },
        { name: 'email_financeiro', type: 'email', required: false },
        { name: 'site', type: 'url', required: false },
        // Seção 4: Responsável Técnico (CRC)
        { name: 'contador_nome', type: 'text', required: true },
        { name: 'contador_crc', type: 'text', required: true },
        {
          name: 'contador_uf_crc',
          type: 'select',
          required: false,
          values: [
            'AC',
            'AL',
            'AP',
            'AM',
            'BA',
            'CE',
            'DF',
            'ES',
            'GO',
            'MA',
            'MT',
            'MS',
            'MG',
            'PA',
            'PB',
            'PR',
            'PE',
            'PI',
            'RJ',
            'RN',
            'RS',
            'RO',
            'RR',
            'SC',
            'SP',
            'SE',
            'TO',
          ],
          maxSelect: 1,
        },
        { name: 'contador_email', type: 'email', required: false },
        { name: 'contador_telefone', type: 'text', required: false },
        // Seção 5: Identidade Visual
        {
          name: 'logo',
          type: 'file',
          maxSelect: 1,
          maxSize: 2097152, // 2MB
          mimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'],
          required: false,
        },
        { name: 'cor_primaria', type: 'text', required: false },
        { name: 'cor_secundaria', type: 'text', required: false },
        // Seção 6: Dados Bancários
        {
          name: 'banco',
          type: 'select',
          required: false,
          values: [
            'Banco do Brasil',
            'Itaú',
            'Bradesco',
            'Santander',
            'Caixa Econômica',
            'Nubank',
            'Inter',
            'Sicoob',
            'Sicredi',
            'BTG Pactual',
            'C6 Bank',
            'Safra',
            'Original',
            'Outro',
          ],
          maxSelect: 1,
        },
        { name: 'agencia', type: 'text', required: false },
        { name: 'conta_corrente', type: 'text', required: false },
        { name: 'chave_pix', type: 'text', required: false },
        // Autodate
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_minha_empresa_user ON minha_empresa (user)',
        'CREATE INDEX idx_minha_empresa_cnpj ON minha_empresa (cnpj)',
      ],
    })
    app.save(minhaEmpresa)
  },
  (app) => {
    try {
      const collection = app.findCollectionByNameOrId('minha_empresa')
      app.delete(collection)
    } catch (_) {}
  },
)
