/// <reference path="../pb_data/types.d.ts" />

migrate(
  (app) => {
    // 1. Criar coleção 'setores'
    // Campos:
    // - nome: text (obrigatório)
    // - descricao: text (opcional)
    // - ativo: bool
    // - ordem: number
    // - ev_ebitda: number
    // - pl: number
    // - pvp: number
    // - ev_receita: number
    // - ev_ebit: number
    // - p_ebitda: number
    // - faixas_indicadores: json (liquidez, rentabilidade, endividamento, etc.)
    // - padrao_sistema: bool (identifica se veio do sistema padrão)
    // - created: autodate
    // - updated: autodate
    //
    // Regras multi-tenant:
    // Qualquer usuário autenticado pode listar e visualizar os setores ativos (ou todos se admin/gestão).
    // Admin tem permissão total de create, update e delete.
    // listRule: "@request.auth.id != ''"
    // viewRule: "@request.auth.id != ''"
    // createRule: "@request.auth.id != ''"
    // updateRule: "@request.auth.id != ''"
    // deleteRule: "@request.auth.id != '' && @request.auth.role = 'admin'"

    let setoresCol
    try {
      setoresCol = app.findCollectionByNameOrId('setores')
    } catch (_) {
      setoresCol = new Collection({
        name: 'setores',
        type: 'base',
        listRule: "@request.auth.id != ''",
        viewRule: "@request.auth.id != ''",
        createRule: "@request.auth.id != ''",
        updateRule: "@request.auth.id != ''",
        deleteRule: "@request.auth.id != '' && @request.auth.role = 'admin'",
        fields: [
          { name: 'nome', type: 'text', required: true },
          { name: 'descricao', type: 'text' },
          { name: 'ativo', type: 'bool' },
          { name: 'ordem', type: 'number' },
          { name: 'padrao_sistema', type: 'bool' },
          // Múltiplos de mercado
          { name: 'ev_ebitda', type: 'number' },
          { name: 'pl', type: 'number' },
          { name: 'pvp', type: 'number' },
          { name: 'ev_receita', type: 'number' },
          { name: 'ev_ebit', type: 'number' },
          { name: 'p_ebitda', type: 'number' },
          // Faixas típicas e benchmarks detalhados
          { name: 'faixas_indicadores', type: 'json' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: [
          'CREATE UNIQUE INDEX idx_setores_nome ON setores (nome)',
          'CREATE INDEX idx_setores_ativo ON setores (ativo)',
          'CREATE INDEX idx_setores_ordem ON setores (ordem)',
        ],
      })
      app.save(setoresCol)
    }

    // 2. Seed inicial dos setores: 10 originais + 19 setores adicionais do mercado brasileiro
    const listaInicial = [
      // === 10 SETORES ORIGINAIS (Preservados exatamente) ===
      {
        nome: 'Serviços',
        descricao: 'Prestação de serviços corporativos, consultorias e terceirização',
        ordem: 1,
        ev_ebitda: 6.5,
        pl: 10.0,
        pvp: 2.2,
        ev_receita: 1.4,
        ev_ebit: 8.5,
        p_ebitda: 5.5,
        faixas: {
          margemLiquida: 14.0,
          margemBruta: 45.0,
          margemEbitda: 22.0,
          roe: 21.0,
          roa: 12.5,
          liquidezCorrente: 1.65,
          liquidezSeca: 1.6,
          endividamentoGeral: 42.0,
          giroAtivo: 1.1,
          coberturaJuros: 4.5,
          pmr: 38,
          pmp: 28,
        },
      },
      {
        nome: 'Comércio',
        descricao: 'Varejo, atacado e distribuição mercantil',
        ordem: 2,
        ev_ebitda: 5.5,
        pl: 9.0,
        pvp: 1.6,
        ev_receita: 0.6,
        ev_ebit: 7.5,
        p_ebitda: 4.8,
        faixas: {
          margemLiquida: 5.5,
          margemBruta: 32.0,
          margemEbitda: 11.0,
          roe: 16.0,
          roa: 7.5,
          liquidezCorrente: 1.35,
          liquidezSeca: 0.75,
          endividamentoGeral: 58.0,
          giroAtivo: 1.45,
          coberturaJuros: 2.8,
          pme: 50,
          pmr: 32,
          pmp: 42,
        },
      },
      {
        nome: 'Indústria',
        descricao: 'Setor industrial, manufatura e transformação',
        ordem: 3,
        ev_ebitda: 5.8,
        pl: 8.5,
        pvp: 1.4,
        ev_receita: 0.9,
        ev_ebit: 8.0,
        p_ebitda: 5.0,
        faixas: {
          margemLiquida: 7.2,
          margemBruta: 28.0,
          margemEbitda: 16.5,
          roe: 14.5,
          roa: 6.8,
          liquidezCorrente: 1.45,
          liquidezSeca: 0.95,
          endividamentoGeral: 52.0,
          giroAtivo: 0.95,
          coberturaJuros: 3.2,
          pme: 65,
          pmr: 48,
          pmp: 45,
        },
      },
      {
        nome: 'Tecnologia',
        descricao: 'Software, SaaS, tecnologia da informação e startups',
        ordem: 4,
        ev_ebitda: 11.0,
        pl: 16.0,
        pvp: 3.8,
        ev_receita: 3.2,
        ev_ebit: 13.5,
        p_ebitda: 9.5,
        faixas: {
          margemLiquida: 18.5,
          margemBruta: 68.0,
          margemEbitda: 28.0,
          roe: 24.0,
          roa: 15.0,
          liquidezCorrente: 2.1,
          liquidezSeca: 2.05,
          endividamentoGeral: 35.0,
          giroAtivo: 0.85,
          coberturaJuros: 6.0,
          pmr: 30,
          pmp: 25,
        },
      },
      {
        nome: 'Agronegócio',
        descricao: 'Produção agrícola, pecuária e agroindústria',
        ordem: 5,
        ev_ebitda: 5.2,
        pl: 7.8,
        pvp: 1.2,
        ev_receita: 0.8,
        ev_ebit: 7.0,
        p_ebitda: 4.5,
        faixas: {
          margemLiquida: 8.5,
          margemBruta: 26.0,
          margemEbitda: 18.0,
          roe: 14.0,
          roa: 6.5,
          liquidezCorrente: 1.4,
          liquidezSeca: 0.8,
          endividamentoGeral: 55.0,
          giroAtivo: 0.8,
          coberturaJuros: 2.9,
          pme: 90,
          pmr: 60,
          pmp: 60,
        },
      },
      {
        nome: 'Construção',
        descricao: 'Construção civil, incorporação e engenharia',
        ordem: 6,
        ev_ebitda: 4.8,
        pl: 7.0,
        pvp: 1.1,
        ev_receita: 0.7,
        ev_ebit: 6.5,
        p_ebitda: 4.2,
        faixas: {
          margemLiquida: 6.5,
          margemBruta: 24.0,
          margemEbitda: 14.0,
          roe: 13.5,
          roa: 5.5,
          liquidezCorrente: 1.3,
          liquidezSeca: 0.65,
          endividamentoGeral: 60.0,
          giroAtivo: 0.75,
          coberturaJuros: 2.6,
          pme: 120,
          pmr: 75,
          pmp: 65,
        },
      },
      {
        nome: 'Saúde',
        descricao: 'Hospitais, clínicas, laboratórios e medicina diagnóstica',
        ordem: 7,
        ev_ebitda: 7.5,
        pl: 12.0,
        pvp: 2.4,
        ev_receita: 1.6,
        ev_ebit: 9.8,
        p_ebitda: 6.5,
        faixas: {
          margemLiquida: 9.5,
          margemBruta: 35.0,
          margemEbitda: 19.0,
          roe: 16.5,
          roa: 8.0,
          liquidezCorrente: 1.5,
          liquidezSeca: 1.35,
          endividamentoGeral: 48.0,
          giroAtivo: 0.9,
          coberturaJuros: 3.8,
          pme: 25,
          pmr: 65,
          pmp: 40,
        },
      },
      {
        nome: 'Educação',
        descricao: 'Instituições de ensino, faculdades, escolas e edtechs',
        ordem: 8,
        ev_ebitda: 7.0,
        pl: 11.5,
        pvp: 2.0,
        ev_receita: 1.5,
        ev_ebit: 9.0,
        p_ebitda: 6.0,
        faixas: {
          margemLiquida: 11.0,
          margemBruta: 42.0,
          margemEbitda: 20.0,
          roe: 17.0,
          roa: 9.0,
          liquidezCorrente: 1.4,
          liquidezSeca: 1.38,
          endividamentoGeral: 46.0,
          giroAtivo: 0.85,
          coberturaJuros: 4.0,
          pme: 5,
          pmr: 42,
          pmp: 30,
        },
      },
      {
        nome: 'Financeiro',
        descricao: 'Fintechs, serviços financeiros, consultoria e assessoria',
        ordem: 9,
        ev_ebitda: 8.0,
        pl: 9.5,
        pvp: 1.8,
        ev_receita: 2.0,
        ev_ebit: 9.5,
        p_ebitda: 7.0,
        faixas: {
          margemLiquida: 16.0,
          margemBruta: 55.0,
          margemEbitda: 25.0,
          roe: 20.0,
          roa: 11.0,
          liquidezCorrente: 1.8,
          liquidezSeca: 1.8,
          endividamentoGeral: 45.0,
          giroAtivo: 0.7,
          coberturaJuros: 5.5,
          pmr: 25,
          pmp: 20,
        },
      },
      {
        nome: 'Outros',
        descricao: 'Média multissetorial de referência geral de mercado',
        ordem: 10,
        ev_ebitda: 6.0,
        pl: 9.5,
        pvp: 1.7,
        ev_receita: 1.0,
        ev_ebit: 8.0,
        p_ebitda: 5.0,
        faixas: {
          margemLiquida: 8.0,
          margemBruta: 35.0,
          margemEbitda: 17.0,
          roe: 15.0,
          roa: 7.5,
          liquidezCorrente: 1.4,
          liquidezSeca: 1.0,
          endividamentoGeral: 50.0,
          giroAtivo: 1.0,
          coberturaJuros: 3.5,
          pme: 45,
          pmr: 45,
          pmp: 40,
        },
      },

      // === NOVOS SETORES DE MERCADO BRASILEIRO ===
      {
        nome: 'Logística e Transporte',
        descricao: 'Transporte rodoviário, armazenagem, fretes e logística integrada',
        ordem: 11,
        ev_ebitda: 5.6,
        pl: 8.8,
        pvp: 1.5,
        ev_receita: 0.85,
        ev_ebit: 7.8,
        p_ebitda: 4.9,
        faixas: {
          margemLiquida: 6.0,
          margemBruta: 26.0,
          margemEbitda: 15.0,
          roe: 15.0,
          roa: 7.0,
          liquidezCorrente: 1.38,
          liquidezSeca: 1.25,
          endividamentoGeral: 56.0,
          giroAtivo: 1.15,
          coberturaJuros: 3.0,
          pmr: 45,
          pmp: 38,
        },
      },
      {
        nome: 'Varejo Alimentício',
        descricao: 'Supermercados, hipermercados, hortifrútis e minimercados',
        ordem: 12,
        ev_ebitda: 4.8,
        pl: 8.2,
        pvp: 1.4,
        ev_receita: 0.45,
        ev_ebit: 6.8,
        p_ebitda: 4.2,
        faixas: {
          margemLiquida: 3.2,
          margemBruta: 24.5,
          margemEbitda: 7.5,
          roe: 16.5,
          roa: 6.5,
          liquidezCorrente: 1.2,
          liquidezSeca: 0.55,
          endividamentoGeral: 62.0,
          giroAtivo: 2.1,
          coberturaJuros: 2.5,
          pme: 30,
          pmr: 15,
          pmp: 45,
        },
      },
      {
        nome: 'Atacado e Distribuição',
        descricao: 'Atacadistas distribuidores, centros logísticos e atacarejo',
        ordem: 13,
        ev_ebitda: 5.2,
        pl: 8.6,
        pvp: 1.5,
        ev_receita: 0.55,
        ev_ebit: 7.2,
        p_ebitda: 4.5,
        faixas: {
          margemLiquida: 4.2,
          margemBruta: 20.0,
          margemEbitda: 8.5,
          roe: 15.5,
          roa: 7.0,
          liquidezCorrente: 1.42,
          liquidezSeca: 0.8,
          endividamentoGeral: 58.0,
          giroAtivo: 1.7,
          coberturaJuros: 2.9,
          pme: 42,
          pmr: 35,
          pmp: 40,
        },
      },
      {
        nome: 'Automotivo',
        descricao: 'Concessionárias, autopeças, montadoras e reparação automotiva',
        ordem: 14,
        ev_ebitda: 5.0,
        pl: 8.0,
        pvp: 1.3,
        ev_receita: 0.65,
        ev_ebit: 7.0,
        p_ebitda: 4.4,
        faixas: {
          margemLiquida: 4.8,
          margemBruta: 22.0,
          margemEbitda: 10.5,
          roe: 14.0,
          roa: 6.2,
          liquidezCorrente: 1.35,
          liquidezSeca: 0.72,
          endividamentoGeral: 57.0,
          giroAtivo: 1.3,
          coberturaJuros: 2.7,
          pme: 55,
          pmr: 40,
          pmp: 48,
        },
      },
      {
        nome: 'Metalúrgico e Mecânico',
        descricao: 'Metalurgia, usinagem, estruturas metálicas e fundição',
        ordem: 15,
        ev_ebitda: 5.4,
        pl: 8.2,
        pvp: 1.35,
        ev_receita: 0.8,
        ev_ebit: 7.4,
        p_ebitda: 4.7,
        faixas: {
          margemLiquida: 6.8,
          margemBruta: 27.0,
          margemEbitda: 15.5,
          roe: 13.8,
          roa: 6.5,
          liquidezCorrente: 1.42,
          liquidezSeca: 0.9,
          endividamentoGeral: 53.0,
          giroAtivo: 0.95,
          coberturaJuros: 3.1,
          pme: 70,
          pmr: 50,
          pmp: 45,
        },
      },
      {
        nome: 'Têxtil e Vestuário',
        descricao: 'Confecção, vestuário, tecidos, calçados e fiação',
        ordem: 16,
        ev_ebitda: 5.1,
        pl: 8.4,
        pvp: 1.3,
        ev_receita: 0.75,
        ev_ebit: 7.1,
        p_ebitda: 4.5,
        faixas: {
          margemLiquida: 6.0,
          margemBruta: 34.0,
          margemEbitda: 13.0,
          roe: 14.2,
          roa: 6.8,
          liquidezCorrente: 1.45,
          liquidezSeca: 0.82,
          endividamentoGeral: 54.0,
          giroAtivo: 1.1,
          coberturaJuros: 2.9,
          pme: 75,
          pmr: 45,
          pmp: 40,
        },
      },
      {
        nome: 'Alimentos e Bebidas',
        descricao: 'Indústria alimentícia, laticínios, frigoríficos, panificação e bebidas',
        ordem: 17,
        ev_ebitda: 6.2,
        pl: 9.8,
        pvp: 1.8,
        ev_receita: 1.1,
        ev_ebit: 8.2,
        p_ebitda: 5.3,
        faixas: {
          margemLiquida: 7.5,
          margemBruta: 33.0,
          margemEbitda: 16.0,
          roe: 17.5,
          roa: 8.5,
          liquidezCorrente: 1.48,
          liquidezSeca: 0.92,
          endividamentoGeral: 51.0,
          giroAtivo: 1.25,
          coberturaJuros: 3.6,
          pme: 40,
          pmr: 35,
          pmp: 42,
        },
      },
      {
        nome: 'Papel, Celulose e Embalagens',
        descricao: 'Papel, papelão ondulado, celulose e embalagens industriais',
        ordem: 18,
        ev_ebitda: 5.5,
        pl: 8.0,
        pvp: 1.3,
        ev_receita: 0.95,
        ev_ebit: 7.5,
        p_ebitda: 4.8,
        faixas: {
          margemLiquida: 8.0,
          margemBruta: 29.0,
          margemEbitda: 20.0,
          roe: 13.5,
          roa: 6.0,
          liquidezCorrente: 1.5,
          liquidezSeca: 1.05,
          endividamentoGeral: 55.0,
          giroAtivo: 0.8,
          coberturaJuros: 3.2,
          pme: 55,
          pmr: 48,
          pmp: 40,
        },
      },
      {
        nome: 'Energia e Utilities',
        descricao: 'Geração, transmissão, distribuição de energia e saneamento',
        ordem: 19,
        ev_ebitda: 7.2,
        pl: 10.5,
        pvp: 1.9,
        ev_receita: 2.2,
        ev_ebit: 9.2,
        p_ebitda: 6.2,
        faixas: {
          margemLiquida: 14.5,
          margemBruta: 42.0,
          margemEbitda: 32.0,
          roe: 18.0,
          roa: 7.5,
          liquidezCorrente: 1.35,
          liquidezSeca: 1.2,
          endividamentoGeral: 60.0,
          giroAtivo: 0.55,
          coberturaJuros: 3.4,
          pmr: 32,
          pmp: 35,
        },
      },
      {
        nome: 'Telecomunicações e Provedores',
        descricao: 'Operadoras de telecom, provedores regionais de internet e fibra óptica',
        ordem: 20,
        ev_ebitda: 5.8,
        pl: 9.0,
        pvp: 1.6,
        ev_receita: 1.5,
        ev_ebit: 8.0,
        p_ebitda: 5.1,
        faixas: {
          margemLiquida: 12.0,
          margemBruta: 50.0,
          margemEbitda: 30.0,
          roe: 16.0,
          roa: 7.8,
          liquidezCorrente: 1.4,
          liquidezSeca: 1.3,
          endividamentoGeral: 52.0,
          giroAtivo: 0.7,
          coberturaJuros: 3.5,
          pmr: 28,
          pmp: 30,
        },
      },
      {
        nome: 'Mídia e Entretenimento',
        descricao: 'Agências de marketing, publicidade, produtoras e eventos',
        ordem: 21,
        ev_ebitda: 6.8,
        pl: 10.8,
        pvp: 2.1,
        ev_receita: 1.6,
        ev_ebit: 8.8,
        p_ebitda: 5.8,
        faixas: {
          margemLiquida: 13.0,
          margemBruta: 48.0,
          margemEbitda: 21.0,
          roe: 19.0,
          roa: 11.0,
          liquidezCorrente: 1.6,
          liquidezSeca: 1.55,
          endividamentoGeral: 44.0,
          giroAtivo: 1.05,
          coberturaJuros: 4.2,
          pmr: 45,
          pmp: 32,
        },
      },
      {
        nome: 'Imobiliário e Propriedades',
        descricao: 'Loteadoras, administradoras prediais, imobiliárias e holdings de bens',
        ordem: 22,
        ev_ebitda: 6.5,
        pl: 8.5,
        pvp: 1.25,
        ev_receita: 1.8,
        ev_ebit: 8.0,
        p_ebitda: 5.5,
        faixas: {
          margemLiquida: 18.0,
          margemBruta: 45.0,
          margemEbitda: 25.0,
          roe: 12.5,
          roa: 6.5,
          liquidezCorrente: 1.55,
          liquidezSeca: 0.95,
          endividamentoGeral: 48.0,
          giroAtivo: 0.45,
          coberturaJuros: 3.2,
          pmr: 60,
          pmp: 40,
        },
      },
      {
        nome: 'Petróleo, Gás e Combustíveis',
        descricao: 'Postos de combustíveis, distribuidoras de GLP e derivados de petróleo',
        ordem: 23,
        ev_ebitda: 4.6,
        pl: 7.5,
        pvp: 1.35,
        ev_receita: 0.35,
        ev_ebit: 6.2,
        p_ebitda: 4.0,
        faixas: {
          margemLiquida: 3.0,
          margemBruta: 14.0,
          margemEbitda: 6.5,
          roe: 18.0,
          roa: 7.2,
          liquidezCorrente: 1.3,
          liquidezSeca: 0.9,
          endividamentoGeral: 60.0,
          giroAtivo: 2.8,
          coberturaJuros: 2.8,
          pme: 10,
          pmr: 12,
          pmp: 20,
        },
      },
      {
        nome: 'Mineração e Extração',
        descricao: 'Extração mineral, pedreiras, areais e agregados para construção',
        ordem: 24,
        ev_ebitda: 4.9,
        pl: 7.2,
        pvp: 1.2,
        ev_receita: 1.2,
        ev_ebit: 6.6,
        p_ebitda: 4.3,
        faixas: {
          margemLiquida: 12.0,
          margemBruta: 38.0,
          margemEbitda: 26.0,
          roe: 15.0,
          roa: 7.5,
          liquidezCorrente: 1.45,
          liquidezSeca: 1.2,
          endividamentoGeral: 49.0,
          giroAtivo: 0.65,
          coberturaJuros: 3.5,
          pme: 30,
          pmr: 45,
          pmp: 35,
        },
      },
      {
        nome: 'Químico e Petroquímico',
        descricao: 'Produtos químicos industriais, tintas, resinas, polímeros e saneantes',
        ordem: 25,
        ev_ebitda: 5.7,
        pl: 8.6,
        pvp: 1.45,
        ev_receita: 0.95,
        ev_ebit: 7.7,
        p_ebitda: 5.0,
        faixas: {
          margemLiquida: 7.8,
          margemBruta: 30.0,
          margemEbitda: 17.0,
          roe: 15.5,
          roa: 7.2,
          liquidezCorrente: 1.5,
          liquidezSeca: 0.95,
          endividamentoGeral: 52.0,
          giroAtivo: 0.95,
          coberturaJuros: 3.3,
          pme: 60,
          pmr: 48,
          pmp: 42,
        },
      },
      {
        nome: 'Farmacêutico e Cosméticos',
        descricao: 'Indústria farmacêutica, cosméticos, perfumaria e farmácias',
        ordem: 26,
        ev_ebitda: 7.8,
        pl: 13.0,
        pvp: 2.6,
        ev_receita: 1.7,
        ev_ebit: 10.2,
        p_ebitda: 6.8,
        faixas: {
          margemLiquida: 10.5,
          margemBruta: 44.0,
          margemEbitda: 20.0,
          roe: 18.5,
          roa: 9.5,
          liquidezCorrente: 1.6,
          liquidezSeca: 1.05,
          endividamentoGeral: 47.0,
          giroAtivo: 1.1,
          coberturaJuros: 4.1,
          pme: 65,
          pmr: 52,
          pmp: 45,
        },
      },
      {
        nome: 'Veterinário e Agropecuário',
        descricao: 'Clínicas veterinárias, pet shops, nutrição animal e insumos agropecuários',
        ordem: 27,
        ev_ebitda: 6.6,
        pl: 10.2,
        pvp: 2.0,
        ev_receita: 1.3,
        ev_ebit: 8.6,
        p_ebitda: 5.6,
        faixas: {
          margemLiquida: 9.0,
          margemBruta: 36.0,
          margemEbitda: 17.5,
          roe: 17.0,
          roa: 8.8,
          liquidezCorrente: 1.52,
          liquidezSeca: 1.02,
          endividamentoGeral: 49.0,
          giroAtivo: 1.15,
          coberturaJuros: 3.7,
          pme: 40,
          pmr: 38,
          pmp: 35,
        },
      },
      {
        nome: 'Contabilidade e Escritórios',
        descricao: 'Escritórios contábeis, advocacia, perícia, auditoria e cartórios',
        ordem: 28,
        ev_ebitda: 6.4,
        pl: 9.8,
        pvp: 2.3,
        ev_receita: 1.5,
        ev_ebit: 8.2,
        p_ebitda: 5.4,
        faixas: {
          margemLiquida: 17.5,
          margemBruta: 52.0,
          margemEbitda: 24.0,
          roe: 23.0,
          roa: 13.5,
          liquidezCorrente: 1.85,
          liquidezSeca: 1.8,
          endividamentoGeral: 38.0,
          giroAtivo: 1.0,
          coberturaJuros: 5.0,
          pmr: 30,
          pmp: 22,
        },
      },
      {
        nome: 'RH, Recrutamento e Treinamento',
        descricao: 'Agências de emprego, recrutamento e seleção, terceirização de RH',
        ordem: 29,
        ev_ebitda: 6.0,
        pl: 9.5,
        pvp: 2.1,
        ev_receita: 1.2,
        ev_ebit: 7.9,
        p_ebitda: 5.1,
        faixas: {
          margemLiquida: 11.5,
          margemBruta: 40.0,
          margemEbitda: 18.0,
          roe: 20.0,
          roa: 11.5,
          liquidezCorrente: 1.7,
          liquidezSeca: 1.68,
          endividamentoGeral: 40.0,
          giroAtivo: 1.2,
          coberturaJuros: 4.4,
          pmr: 35,
          pmp: 25,
        },
      },
    ]

    const col = app.findCollectionByNameOrId('setores')
    for (const item of listaInicial) {
      try {
        app.findFirstRecordByData('setores', 'nome', item.nome)
        // Já existe, pula
      } catch (_) {
        const rec = new Record(col)
        rec.set('nome', item.nome)
        rec.set('descricao', item.descricao)
        rec.set('ativo', true)
        rec.set('ordem', item.ordem)
        rec.set('padrao_sistema', true)
        rec.set('ev_ebitda', item.ev_ebitda)
        rec.set('pl', item.pl)
        rec.set('pvp', item.pvp)
        rec.set('ev_receita', item.ev_receita)
        rec.set('ev_ebit', item.ev_ebit)
        rec.set('p_ebitda', item.p_ebitda)
        rec.set('faixas_indicadores', item.faixas)
        app.save(rec)
      }
    }
  },
  (app) => {
    try {
      const col = app.findCollectionByNameOrId('setores')
      app.delete(col)
    } catch (_) {}
  },
)
